# Task 1 : Data Cleaning & Preprocessing

## Objectives : 
    - Load the dataset using Pandas.
    - Idantify and handle missing values.
    - Remove duplicate rows & standardize inconsistent data formats.

### 1. Importing Libraries

In [45]:
import pandas as pd

### 2. Reading the CSV file

In [48]:
a = pd.read_csv(r"C:\Users\Rudra Pratap Swain\OneDrive\Desktop\CodVeda\DATASETS\Churn Prdiction Data\churn-bigml-80.csv")
print(a)

     State  Account length  Area code International plan Voice mail plan  \
0       KS             128        415                 No             Yes
1       OH             107        415                 No             Yes
2       NJ             137        415                 No              No
3       OH              84        408                Yes              No
4       OK              75        415                Yes              No
...    ...             ...        ...                ...             ...
2661    SC              79        415                 No              No
2662    AZ             192        415                 No             Yes
2663    WV              68        415                 No              No
2664    RI              28        510                 No              No
2665    TN              74        415                 No             Yes

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1              110
1                        26              161.6              123
2                         0              243.4              114
3                         0              299.4               71
4                         0              166.7              113
...                     ...                ...              ...
2661                      0              134.7               98
2662                     36              156.2               77
2663                      0              231.1               57
2664                      0              180.8              109
2665                     25              234.4              113

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                45.07              197.4               99             16.78
1                27.47              195.5              103             16.62
2                41.38              121.2              110             10.30
3                50.90               61.9               88              5.26
4                28.34              148.3              122             12.61
...                ...                ...              ...               ...
2661             22.90              189.7               68             16.12
2662             26.55              215.5              126             18.32
2663             39.29              153.4               55             13.04
2664             30.74              288.8               58             24.55
2665             39.85              265.9               82             22.60

      Total night minutes  Total night calls  Total night charge  \
0                   244.7                 91               11.01
1                   254.4                103               11.45
2                   162.6                104                7.32
3                   196.9                 89                8.86
4                   186.9                121                8.41
...                   ...                ...                 ...
2661                221.4                128                9.96
2662                279.1                 83               12.56
2663                191.3                123                8.61
2664                191.9                 91                8.64
2665                241.4                 77               10.86

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70
1                   13.7                 3               3.70
2                   12.2                 5               3.29
3                    6.6                 7               1.78
4                   10.1                 3               2.73
...                  ...               ...                ...
2661                11.8                 5               3.19
2662                 9.9                 6               2.67
2663                 9.6                 4               2.59
2664                14.1                 6               3.81
2665                13.7                 4               3.70

      Customer service calls  Churn
0                          1  False
1                          1  False
2                          0  False
3                          2  False
4                          3  False
...                      ...    ...
2661                       2  False
2662                       2  False
2663                       3  False
2664                       2  False
2665                       0  False

[2666 rows x 20 columns]

### 3. Checking the Null values

In [51]:
a.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

### 4. Verifying the data types

In [54]:
a.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls             int64
Total day charge          float64
Total eve minutes         float64
Total eve calls             int64
Total eve charge          float64
Total night minutes       float64
Total night calls           int64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls      int64
Churn                        bool
dtype: object

In [56]:
a.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

### 5. Checking unique values

In [59]:
for i in a.columns:
    print(i,' : \n',a[i].unique())

State  :
 ['KS' 'OH' 'NJ' 'OK' 'AL' 'MA' 'MO' 'WV' 'RI' 'IA' 'MT' 'ID' 'VT' 'VA'
 'TX' 'FL' 'CO' 'AZ' 'NE' 'WY' 'IL' 'NH' 'LA' 'GA' 'AK' 'MD' 'AR' 'WI'
 'OR' 'DE' 'IN' 'UT' 'CA' 'SD' 'NC' 'WA' 'MN' 'NM' 'NV' 'DC' 'NY' 'KY'
 'ME' 'MS' 'MI' 'SC' 'TN' 'PA' 'HI' 'ND' 'CT']
Account length  :
 [128 107 137  84  75 118 121 147 141  74 168  95  62  85  93  76  73  77
 130 132 174  57  54  20 142 172  12  72  78 136 149  98 135  34 160  64
  59  97  52  60  96  87  81 125 116  38  40  43 113 126 150 138 162  90
  50  82 144  70  55 106  94 111  80 104  99 120 122 157 103  36 112  46
  41 193  61  92 131 163  91 127 110 117 140  83 145  56 151 139 115 146
 185 148  68 179  67  19 170 164  51  63  53 105  66  86  35  88 123 100
 108  22  33 114  24 119 101  49  48  71 167 166 158 196 209  16  39 173
 129 143  89  44  79  31  37 159 194 154  45  32  21 133  25 224  58 155
  11 109 165  18 161 124  30 176  47 190 152  65 186 171 102  28 153 169
  13  42 189  69  27 134 156 243  23 205 200   5   9 178 181 182 177 210
 180   3  10   2  17 212   1  29 192 195   6 225 184 197  15 183 202   8
 217   4 188   7 204 201 221]
Area code  :
 [415 408 510]
International plan  :
 ['No' 'Yes']
Voice mail plan  :
 ['Yes' 'No']
Number vmail messages  :
 [25 26  0 24 37 27 33 39 41 28 30 34 46 35 21 42 36 22 23 43 31 38 40 29
 18 32 17 45 16 14 20 19 15 12 47  8 44  4 10 13 50  9]
Total day minutes  :
 [265.1 161.6 243.4 ... 106.6 231.1 180.8]
Total day calls  :
 [110 123 114  71 113  98  88  79  84 127  96  70 139  66  90 117  89 112
  86  76 115  73 109  95 105 121 118  94  80  64 106 102  85  82  77  67
  97 133 135 108  57  83 129 103  92  74  93 101 146  99 104 125  61 100
  87 131  65 124 119  52  68 107  47 116 120 151 126  91 122 111 145  78
 136 140  81 128  69 158 134 130  63  53  75 141  59 132 138 137  54  58
  62  36  72  40 150 147  56  51  55 148  48  60  42   0  45 160 149 144
 143 152 142 156  49 157  44]
Total day charge  :
 [45.07 27.47 41.38 ... 18.12 39.29 30.74]
Total eve minutes  :
 [197.4 195.5 121.2 ... 153.4 288.8 265.9]
Total eve calls  :
 [ 99 103 110  88 122 101 108  94 111 148  71  75  76  90  65  93 121  72
 112 100  84  63 107 115 119 102 116  92  85  98 118  74  58  96  67  62
  77 126 142  64  97 104  80  83 117  79  95 105  81 113 109  48  82  86
  87 123 114 140 128 106  60 125  46 138 129  89 133 136  57 135 139  51
  70  78 151  91 152 120  66 127 132 137  73 143  68  61  42  54 149 124
 134 131  69 130  52  49  59 146 147  55  12  50 157  56  45 144  36 156
  53 141  44 153 154 155 150  43   0 145 159 170]
Total eve charge  :
 [16.78 16.62 10.3  ... 13.04 24.55 22.6 ]
Total night minutes  :
 [244.7 254.4 162.6 ... 221.4 279.1 191.3]
Total night calls  :
 [ 91 103 104  89 121 118  96  97  94 128 115  99  75 108  74 133  64  78
  68 102 148  98  90 116  71 107 135  92  86 127  79  87 129  77  95  54
 106  53  67 139  60 100  61 109 105 111  73  76 119  88  84  57  62 137
 113 114 126 122 123 117  82 120  80 130 134  59 112 132 142 101  69 131
 110  83  93 124 136  81  66 143  55  56  70  85  46 152  44 145  58  50
  42 153 125  49 138  72 154 140 141 146  63  65  51 151 158 157 147 144
 149 166  33 155 156  38  36 150  48 164]
Total night charge  :
 [11.01 11.45  7.32  8.86  8.41  9.18  9.57  9.53 14.69  8.82  6.35  8.65
  9.14  4.02  5.83  7.46  8.68  9.4   9.43  8.18 10.67 11.28  8.22  4.59
  8.17 11.27 11.08 13.2  12.61  9.61  6.88 10.25  4.58  8.47  8.45  5.5
 14.02  8.03 11.94  7.34 10.9   3.18 10.66 11.21 10.28 12.16  6.34  8.15
  8.52  7.5   7.48 11.95  7.15  9.63  7.1   5.82  6.91  6.69 13.29 11.46
  7.76  6.86  8.16 12.15  7.79 10.29 10.08 12.53  7.91 10.02  8.61  8.53
  8.21  9.09  4.93 11.39 11.88  5.75  8.59  7.52  7.21  8.1  11.19  8.55
  9.76 10.86  5.36 10.03 11.15  6.22  2.59  7.65  7.99  9.    6.4   9.94
  5.08 10.23 11.36  6.97 10.16  7.88 11.91  6.61 11.76  9.27  9.29 11.12
 10.69  8.8  11.85  7.14  8.71 11.42  4.94  9.02 11.22  4.97  5.45 12.91
  7.75  6.32 12.13 11.97  6.93 11.66  7.42  6.19 11.41 10.33 10.65 11.92
  4.77  4.38  7.69  8.78  9.36  9.05 12.7   6.16  6.05 10.85  8.93  8.42
 10.4   5.05 10.71  9.37  6.75  8.12 11.77 11.49 11.06 11.25 11.03 10.82
  8.91  8.57 10.05 11.7  10.17  8.74  5.51 11.11  3.29 10.13  6.8   8.49
  9.55 11.02  7.84 10.62  9.97  3.44  9.79  8.89  8.14  6.94 10.49 10.57
  6.29  8.79 10.04 12.41 15.97  9.1  11.78 12.75 12.56  8.63  8.02 10.42
  8.7   7.62  8.33 13.12 10.46  8.32  9.04  9.28 10.76  9.15 11.44  6.48
 10.81 12.66  8.75 13.05 11.48  5.63  6.6  11.68  6.41  9.32  9.62  8.25
  8.26 11.96  9.9   9.23  5.58  7.22  6.64 12.29 12.93 11.32  6.85  7.03
  8.48  3.59  5.86  8.88  6.23  7.61  7.66 13.63  7.9  11.82 12.38  7.47
  6.08  8.4   5.74 10.94 10.35 10.68  4.34  5.14  8.24  9.99  8.64 11.43
  5.79 10.14 12.11  7.53 12.46  8.46  8.95  9.84 10.8  11.23 10.15  9.21
 14.46  6.67 12.83  9.66 10.48  8.36  4.84  8.39 10.2   7.23  9.06  8.94
 11.13  8.87  9.87 10.73  9.56 10.77  7.73  3.47 11.86  8.11  9.78  9.65
  7.    7.39  9.88  6.56  5.92  6.95 15.71  8.06  4.86  5.21  6.92  6.15
 12.62 12.26  8.19 11.65 11.62 10.83  7.92  7.35 13.01  9.91 13.26 12.22
 11.58 10.06  5.97 10.99  8.38  8.08  5.71  3.41 11.34  9.98 12.63 11.79
  7.64  6.58 10.84 10.22  6.52  7.63  5.11  5.89 10.78  8.97 10.44 10.5
  9.35  5.66  9.83  5.44 11.93 12.06  8.85  8.66  6.73 10.21 11.59 13.87
  8.04  7.77 10.39  5.54  6.62  7.6  13.33  6.24  6.3  11.07  6.79  8.28
  9.03  9.71  8.07 12.14  7.54  7.67  5.47 13.46  8.81  8.51  6.43 12.01
 12.08  7.07  6.51  6.84  9.48 13.78 11.54 11.67  9.38  8.13 10.79  9.72
  7.13  4.72 11.55  4.64  8.09  6.07  3.51  6.83  9.31  9.51  5.32 13.82
  8.44  5.77 10.96  8.73 11.74  8.9  10.47  7.85 12.1  10.92  4.74  9.3
  9.74 10.43 12.95 10.18  9.54  7.89 12.36  8.54 10.07  9.46  9.17  7.3
 11.16  9.16 10.19 10.88  5.8   4.55  8.31 14.43  8.3   8.2  11.31 10.54
  6.03  6.42  6.02  7.44  7.51  6.06 13.1   9.49  6.14  8.76  6.65 11.89
 10.56  6.72  8.29 12.09  5.39  2.96  7.59  7.24  4.28  9.7  13.3   9.33
  5.01 11.71  8.43  9.8   3.61  6.96  6.59  6.44 11.61 12.81 10.87 13.84
  5.03 13.03  5.17  2.03  8.83 10.34  9.34  9.95  7.11  9.22 11.05  9.89
  9.39 14.06 10.26 13.31 15.43 16.39  6.27 11.5  12.48 13.53 12.24  8.69
 10.52  9.2  11.51  7.8   8.58  8.72  6.78  8.6   5.78  7.41  5.85  5.76
 12.07  9.6   9.96  8.84 12.39  8.01 10.1  13.45  2.85 11.52  2.45  5.28
 11.73 10.75  6.76  6.    7.83  7.58 13.69  7.93  7.68  5.49  9.64  7.18
 11.47  9.19  7.7  10.74  9.12  4.75  7.78 11.63  7.55  2.25  9.45  9.86
  7.71  4.95  7.4   7.43 11.33  6.82  9.58 13.7   1.97 10.89 12.77  5.23
  5.27  9.41  7.33  7.29  4.23  6.12  7.57  3.67 12.69 14.5   5.95  7.87
  5.96  5.94 12.23  4.9   5.81 12.33  6.89  9.67 12.87  9.26  6.04 13.13
 11.87  5.42  5.73  9.47  8.05  3.71 15.86 11.69  6.46 10.45 12.9  11.04
  5.41  6.37 12.21  6.77 12.65  7.86  9.44  4.3   7.38  6.39 13.37  5.02
 10.63  2.86 17.19  8.67 10.09  8.37  6.9  10.38  7.36 10.27  6.11  4.45
 11.9  15.01 12.84  6.09 10.61  7.45  6.45 11.17 11.72  7.56 11.38  4.42
  9.81  5.56  6.01 10.12  8.5  12.4  16.99  5.68 11.64  3.78  9.73  7.82
 13.74 12.71 10.98 10.01  9.52  7.31 11.35  9.5  14.03 11.84  7.72 13.22
 10.7   8.99  4.68 13.02  9.77 12.58 12.35 12.2  11.4  13.91  3.57 14.65
 13.8  12.28  5.99  5.13 10.72 12.86 14.   12.17  4.71  6.28  8.    5.91
  5.2  12.    7.27 12.3  12.02 12.88  7.28  5.4  12.04  5.24  6.63 10.41
 13.41  9.08  7.08 13.5   5.35 11.83 10.3   5.3  10.32  5.15 12.67 10.64
 10.6  12.59  5.57  3.94  4.41  8.35 13.27 10.24  4.25 12.89 12.5  11.29
  3.25 11.53  7.05  7.26  4.1  10.37  4.98  6.74 12.52 14.56  8.34 10.59
  9.07  3.82 13.97  6.5  13.58 10.93  6.13 14.32 11.14 14.18 10.31  4.46
 11.26 10.95  9.82  4.83  7.19  7.74  9.69 14.13  7.16  4.27  6.53  7.98
 13.66  8.77 14.78 11.2   9.93 11.    5.29  9.92  6.66  4.29 11.1  10.51
  8.96 12.49  4.04 12.94  7.09  6.71  7.94  5.31  5.98  9.85  7.2  14.82
  7.25  9.75 13.21  7.01 12.32 10.58  4.92  6.87  6.2   4.47 11.98  4.54
  9.59 10.11  5.37  5.33  5.7  12.18  8.98  5.1  13.95  4.67 11.18  4.44
  4.73  2.55  6.31  2.43  9.24  7.37 13.42 12.42 11.8  14.45 13.23 10.55
 12.6  13.18  7.17 12.19 14.81  6.55  6.21  5.55 11.3  12.27 13.98  8.23
 15.49  6.47 11.57 13.48 13.59 13.25 17.77 13.9   3.97 11.56 14.08 13.6
  7.49  6.26  4.61  6.98 12.76 15.76  3.6  12.8   7.95  5.9   7.97  5.
 12.45 10.97  5.88 12.34 12.03 14.97 15.06 12.85  5.84  6.54  8.27  6.38
 11.24 12.64  7.06  5.38  8.62  6.49 10.    4.51  3.93  2.4  11.75  4.7
  9.25 15.85  6.81 14.25 14.09 16.42  6.7  12.96 14.67 12.12  6.68 11.81
  5.06 13.16  2.13 13.17  5.12  9.11  5.65 12.37 10.53]
Total intl minutes  :
 [10.  13.7 12.2  6.6 10.1  6.3  7.5  7.1 11.2  9.1 12.3 13.1 13.8  8.1
 13.  10.6  5.7  9.5 10.3 15.5 14.7 14.2 12.6 11.8  8.3 10.5 11.1  9.4
 14.6  9.2  3.5  8.5  7.4 11.   7.8  6.8  9.3  9.7 10.2  8.   5.8 12.
 11.4 11.6  8.2  6.2 12.1  7.3  6.1 11.7 15.  13.2  9.8 12.4 10.9 13.9
  7.9  8.7  5.3  4.4 11.3  9.6 13.3 20.   7.2  6.4 14.1 14.3  6.9 11.5
 15.8 12.8 16.2  0.  11.9  9.9  8.4 10.8  9.   8.9  8.8 13.4 10.7 17.6
  4.7  7.7 13.5 12.9 14.4 14.5  6.7 15.4  5.9 18.9  7.6  5.  12.5  8.6
  7.  14.  12.7 18.  16.  14.8  3.7  4.8 15.3  6.  13.6 17.2 17.5  5.4
 18.2  3.6 16.5  4.6  5.1  4.1  6.5 15.6 10.4 16.4 16.7  1.3 15.2 15.1
 15.9  5.5 16.1 14.9  4.  16.9  5.2  4.2 17.   3.9  2.2  5.6 15.7  4.5
 17.9 16.3  4.9 17.3  3.8 18.4 17.8  4.3  2.9  3.1  3.3  2.6  3.4  1.1
 16.6  2.1  2.4  2.5]
Total intl calls  :
 [ 3  5  7  6  2  4 19 10  9 15  8  1 11  0 12 13 18 14 16 20 17]
Total intl charge  :
 [2.7  3.7  3.29 1.78 2.73 1.7  2.03 1.92 3.02 2.46 3.32 3.54 3.73 2.19
 3.51 2.86 1.54 2.57 2.78 4.19 3.97 3.83 3.4  3.19 2.24 2.84 3.   2.54
 3.94 2.48 0.95 2.3  2.   2.97 2.11 1.84 2.51 2.62 2.75 2.16 1.57 3.24
 3.08 3.13 2.21 1.67 3.27 1.97 1.65 3.16 4.05 3.56 2.65 3.35 2.94 3.75
 2.13 2.35 1.43 1.19 3.05 2.59 3.59 5.4  1.94 1.73 3.81 3.86 1.86 3.11
 4.27 3.46 4.37 0.   3.21 2.67 2.27 2.92 2.43 2.4  2.38 3.62 2.89 4.75
 1.27 2.08 3.65 3.48 3.89 3.92 1.81 4.16 1.59 5.1  2.05 1.35 3.38 2.32
 1.89 3.78 3.43 4.86 4.32 4.   1.   1.3  4.13 1.62 3.67 4.64 4.73 1.46
 4.91 0.97 4.46 1.24 1.38 1.11 1.76 4.21 2.81 4.43 4.51 0.35 4.1  4.08
 4.29 1.49 4.35 4.02 1.08 4.56 1.4  1.13 4.59 1.05 0.59 1.51 4.24 1.22
 4.83 4.4  1.32 4.67 1.03 4.97 4.81 1.16 0.78 0.84 0.89 0.7  0.92 0.3
 4.48 0.57 0.65 0.68]
Customer service calls  :
 [1 0 2 3 4 5 7 9 6 8]
Churn  :
 [False  True]

### 6. Describing Dataset

In [62]:
a.describe(include='all')

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
count,2666,2666.000000,2666.000000,2666,2666,2666.000000,2666.00000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666.000000,2666
unique,51,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,WV,NaN,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,88,NaN,NaN,2396,1933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2278
mean,NaN,100.620405,437.438860,NaN,NaN,8.021755,179.48162,100.310203,30.512404,200.386159,100.023631,17.033072,201.168942,100.106152,9.052689,10.237022,4.467367,2.764490,1.562641,NaN
std,NaN,39.563974,42.521018,NaN,NaN,13.612277,54.21035,19.988162,9.215733,50.951515,20.161445,4.330864,50.780323,19.418459,2.285120,2.788349,2.456195,0.752812,1.311236,NaN
min,NaN,1.000000,408.000000,NaN,NaN,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,43.700000,33.000000,1.970000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,73.000000,408.000000,NaN,NaN,0.000000,143.40000,87.000000,24.380000,165.300000,87.000000,14.050000,166.925000,87.000000,7.512500,8.500000,3.000000,2.300000,1.000000,NaN
50%,NaN,100.000000,415.000000,NaN,NaN,0.000000,179.95000,101.000000,30.590000,200.900000,100.000000,17.080000,201.150000,100.000000,9.050000,10.200000,4.000000,2.750000,1.000000,NaN
75%,NaN,127.000000,510.000000,NaN,NaN,19.000000,215.90000,114.000000,36.700000,235.100000,114.000000,19.980000,236.475000,113.000000,10.640000,12.100000,6.000000,3.270000,2.000000,NaN
max,NaN,243.000000,510.000000,NaN,NaN,50.000000,350.80000,160.000000,59.640000,363.700000,170.000000,30.910000,395.000000,166.000000,17.770000,20.000000,20.000000,5.400000,9.000000,NaN

### 7. Dataset Info

In [65]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   2666 non-null   object
 1   Account length          2666 non-null   int64
 2   Area code               2666 non-null   int64
 3   International plan      2666 non-null   object
 4   Voice mail plan         2666 non-null   object
 5   Number vmail messages   2666 non-null   int64
 6   Total day minutes       2666 non-null   float64
 7   Total day calls         2666 non-null   int64
 8   Total day charge        2666 non-null   float64
 9   Total eve minutes       2666 non-null   float64
 10  Total eve calls         2666 non-null   int64
 11  Total eve charge        2666 non-null   float64
 12  Total night minutes     2666 non-null   float64
 13  Total night calls       2666 non-null   int64
 14  Total night charge      2666 non-null   float64
 15  Total intl minutes      2666 non-null   float64
 16  Total intl calls        2666 non-null   int64
 17  Total intl charge       2666 non-null   float64
 18  Customer service calls  2666 non-null   int64
 19  Churn                   2666 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 398.5+ KB

### 8. Encoding Categorical Features

#### Label Encoder
    - Label Encoder is used to convert text data into numerical datas.
    - It is done because most of the ML models can't directly work with the text datas.
    - Therefore we need to encode them.

In [69]:
from sklearn.preprocessing import LabelEncoder

In [71]:
le = LabelEncoder()
a['State'] = le.fit_transform(a['State'])

In [73]:
le1 = LabelEncoder()
a['International plan'] = le1.fit_transform(a['International plan'])

In [75]:
le2 = LabelEncoder()
a['Voice mail plan'] = le2.fit_transform(a['Voice mail plan'])

In [77]:
le3 = LabelEncoder()
a['Churn'] = le3.fit_transform(a['Churn'])

In [80]:
a.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,16,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,35,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,31,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,35,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,36,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

### 9. Standardize the numerical features

#### Standard Scaler
    - StandardScaler is used to standardize the numerical features to have a mean=0 & standard deviation=1.
    - It ensures that all features contribute equally.

In [84]:
from sklearn.preprocessing import StandardScaler

In [88]:
sc = StandardScaler()
a_scaled = sc.fit_transform(a)

### 10. Final Dataset

In [91]:
a_final = pd.DataFrame(a_scaled, columns=a.columns, index=a.index)

In [93]:
a_final.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,-0.672700,0.692163,-0.527811,-0.335690,1.623917,1.247508,1.579670,0.484868,1.579942,-0.058619,-0.050781,-0.058445,0.857403,-0.469031,0.856707,-0.085020,-0.597527,-0.085681,-0.429172,-0.412704
1,0.600844,0.161278,-0.527811,-0.335690,1.623917,1.320985,-0.329918,1.135375,-0.330194,-0.095916,0.147654,-0.095397,1.048458,0.149054,1.049293,1.242179,-0.597527,1.242921,-0.429172,-0.412704
2,0.332730,0.919686,-0.527811,-0.335690,-0.615795,-0.589414,1.179302,0.685024,1.179465,-1.554439,0.494917,-1.554963,-0.759668,0.200561,-0.758391,0.704125,0.216894,0.698194,-1.191955,-0.412704
3,0.600844,-0.420168,-0.692467,2.978938,-0.615795,-0.589414,2.212509,-1.466653,2.212675,-2.718509,-0.596479,-2.718922,-0.084083,-0.572045,-0.084339,-1.304609,1.031314,-1.307995,0.333610,-0.412704
4,0.667873,-0.647691,-0.527811,2.978938,-0.615795,-0.589414,-0.235822,0.634985,-0.235772,-1.022461,1.090224,-1.021482,-0.281046,1.076181,-0.281303,-0.049150,-0.597527,-0.045823,1.096392,-0.412704

### 11. Final Verfication

In [96]:
print(a_final)

         State  Account length  Area code  International plan  \
0    -0.672700        0.692163  -0.527811           -0.335690
1     0.600844        0.161278  -0.527811           -0.335690
2     0.332730        0.919686  -0.527811           -0.335690
3     0.600844       -0.420168  -0.692467            2.978938
4     0.667873       -0.647691  -0.527811            2.978938
...        ...             ...        ...                 ...
2661  0.935988       -0.546569  -0.527811           -0.335690
2662 -1.544073        2.310100  -0.527811           -0.335690
2663  1.539245       -0.824652  -0.527811           -0.335690
2664  0.868959       -1.835863   1.706797           -0.335690
2665  1.070045       -0.672971  -0.527811           -0.335690

      Voice mail plan  Number vmail messages  Total day minutes  \
0            1.623917               1.247508           1.579670
1            1.623917               1.320985          -0.329918
2           -0.615795              -0.589414           1.179302
3           -0.615795              -0.589414           2.212509
4           -0.615795              -0.589414          -0.235822
...               ...                    ...                ...
2661        -0.615795              -0.589414          -0.826226
2662         1.623917               2.055754          -0.429549
2663        -0.615795              -0.589414           0.952365
2664        -0.615795              -0.589414           0.024324
2665         1.623917               1.247508           1.013251

      Total day calls  Total day charge  Total eve minutes  Total eve calls  \
0            0.484868          1.579942          -0.058619        -0.050781
1            1.135375         -0.330194          -0.095916         0.147654
2            0.685024          1.179465          -1.554439         0.494917
3           -1.466653          2.212675          -2.718509        -0.596479
4            0.634985         -0.235772          -1.022461         1.090224
...               ...               ...                ...              ...
2661        -0.115600         -0.826178          -0.209771        -1.588658
2662        -1.166419         -0.430042           0.296687         1.288660
2663        -2.167199          0.952636          -0.922347        -2.233574
2664         0.434829          0.024701           1.735580        -2.084747
2665         0.634985          1.013413           1.286049        -0.894133

      Total eve charge  Total night minutes  Total night calls  \
0            -0.058445             0.857403          -0.469031
1            -0.095397             1.048458           0.149054
2            -1.554963            -0.759668           0.200561
3            -2.718922            -0.084083          -0.572045
4            -1.021482            -0.281046           1.076181
...                ...                  ...                ...
2661         -0.210869             0.398478           1.436730
2662          0.297208             1.534958          -0.881087
2663         -0.922176            -0.194382           1.179195
2664          1.735990            -0.182564          -0.469031
2665          1.285649             0.792405          -1.190130

      Total night charge  Total intl minutes  Total intl calls  \
0               0.856707           -0.085020         -0.597527
1               1.049293            1.242179         -0.597527
2              -0.758391            0.704125          0.216894
3              -0.084339           -1.304609          1.031314
4              -0.281303           -0.049150         -0.597527
...                  ...                 ...               ...
2661            0.397126            0.560644          0.216894
2662            1.535136           -0.120891          0.624104
2663           -0.193763           -0.228501         -0.190317
2664           -0.180632            1.385660          0.624104
2665            0.791053            1.242179         -0.190317

      Total intl charge  Customer service calls     Churn
0             -0.085681               -0.429172 -0.412704
1              1.242921               -0.429172 -0.412704
2              0.698194               -1.191955 -0.412704
3             -1.307995                0.333610 -0.412704
4             -0.045823                1.096392 -0.412704
...                 ...                     ...       ...
2661           0.565334                0.333610 -0.412704
2662          -0.125539                0.333610 -0.412704
2663          -0.231828                1.096392 -0.412704
2664           1.389067                0.333610 -0.412704
2665           1.242921               -1.191955 -0.412704

[2666 rows x 20 columns]

In [99]:
a_final.to_csv("Cleaned Churn 80 Dataset.csv", index=False)